-- MySQL Script generated by MySQL Workbench
-- Sat Jan 31 15:44:12 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`VrstaKorisnika`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VrstaKorisnika` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Korisnik` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(30) NOT NULL,
  `Email` VARCHAR(30) NOT NULL,
  `GodinaRodjenja` INT NOT NULL,
  `ProfilnaSlika` VARCHAR(50) NULL,
  `TrenutnoStanjeNovca` FLOAT NOT NULL,
  `VrstaKorisnika_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `VrstaKorisnika_ID`),
  INDEX `fk_Korisnik_VrstaKorisnika_idx` (`VrstaKorisnika_ID` ASC),
  CONSTRAINT `fk_Korisnik_VrstaKorisnika`
    FOREIGN KEY (`VrstaKorisnika_ID`)
    REFERENCES `mydb`.`VrstaKorisnika` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proizvod`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proizvod` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(30) NOT NULL,
  `Opis` VARCHAR(100) NOT NULL,
  `Cena` FLOAT NOT NULL,
  `KolicinaNaStanju` INT NOT NULL,
  `Popust` FLOAT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kupovina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kupovina` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DatumKupovine` DATE NOT NULL,
  `UkupnaCena` FLOAT NOT NULL,
  `Korisnik_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Kupovina_Korisnik1_idx` (`Korisnik_ID` ASC),
  CONSTRAINT `fk_Kupovina_Korisnik1`
    FOREIGN KEY (`Korisnik_ID`)
    REFERENCES `mydb`.`Korisnik` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Komentar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Komentar` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Naslov` VARCHAR(30) NOT NULL,
  `Tekst` VARCHAR(200) NOT NULL,
  `Proizvod_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Komentar_Proizvod1_idx` (`Proizvod_ID` ASC),
  CONSTRAINT `fk_Komentar_Proizvod1`
    FOREIGN KEY (`Proizvod_ID`)
    REFERENCES `mydb`.`Proizvod` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proizvod_has_Korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proizvod_has_Korisnik` (
  `Proizvod_ID` INT NOT NULL,
  `Korisnik_ID` INT NOT NULL,
  PRIMARY KEY (`Proizvod_ID`, `Korisnik_ID`),
  INDEX `fk_Proizvod_has_Korisnik_Korisnik1_idx` (`Korisnik_ID` ASC),
  INDEX `fk_Proizvod_has_Korisnik_Proizvod1_idx` (`Proizvod_ID` ASC),
  CONSTRAINT `fk_Proizvod_has_Korisnik_Proizvod1`
    FOREIGN KEY (`Proizvod_ID`)
    REFERENCES `mydb`.`Proizvod` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Proizvod_has_Korisnik_Korisnik1`
    FOREIGN KEY (`Korisnik_ID`)
    REFERENCES `mydb`.`Korisnik` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proizvod_U_Korpi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proizvod_U_Korpi` (
  `Proizvod_ID` INT NOT NULL,
  `Kolicina` INT NOT NULL,
  `UkupnaCena` FLOAT NOT NULL,
  `Korisnik_ID` INT NOT NULL,
  PRIMARY KEY (`Proizvod_ID`),
  INDEX `fk_Korpa_has_Proizvod_Proizvod1_idx` (`Proizvod_ID` ASC),
  INDEX `fk_Proizvod_U_Korpi_Korisnik1_idx` (`Korisnik_ID` ASC),
  CONSTRAINT `fk_Korpa_has_Proizvod_Proizvod1`
    FOREIGN KEY (`Proizvod_ID`)
    REFERENCES `mydb`.`Proizvod` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Proizvod_U_Korpi_Korisnik1`
    FOREIGN KEY (`Korisnik_ID`)
    REFERENCES `mydb`.`Korisnik` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
